# Generated by Django 3.0.6 on 2020-07-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FY2020_2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Division', models.CharField(choices=[('Corporate Services Division', 'Corporate Services Division'), ('Office of the CEO', 'Corporate Services Division'), ('Office of the Minister', 'Corporate Services Division'), ('Information Technology and Communication Division', 'Corporate Services Division'), ('Finacial Framework Division', 'Corporate Services Division'), ('Procurement Division', 'Corporate Services Division'), ('Treasury Division', 'Corporate Services Division'), ('Budget Division', 'Corporate Services Division'), ('Aid and Projects Division', 'Corporate Services Division'), ('Economic and Fiscal Policy Division', 'Corporate Services Division'), ('Resilience Division', 'Corporate Services Division')], max_length=200, null=True)),
                ('Position', models.CharField(max_length=200, null=True)),
                ('Band', models.CharField(max_length=20, null=True)),
                ('Attendance', models.CharField(max_length=200)),
                ('Time_In', models.DateTimeField(null=True)),
                ('Time_Out', models.DateTimeField(null=True)),
                ('Remarks', models.CharField(max_length=500)),
                ('Date_Created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='Division',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Band',
            field=models.CharField(choices=[('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S')], max_length=20, null=True),
        ),
    ]
