# Generated by Django 3.0.6 on 2020-07-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20200719_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fy2020_2021',
            name='Attendance',
            field=models.CharField(choices=[('On Duty', 'On Duty'), ('Late', 'Late'), ('Casual Leave', 'Casual Leave'), ('Annual Leave', 'Annual Leave'), ('Sick Leave', 'Sick Leave'), ('In Lieu', 'In Lieu'), ('NOP', 'NOP')], max_length=200),
        ),
        migrations.AlterField(
            model_name='fy2020_2021',
            name='Division',
            field=models.CharField(choices=[('Corporate Services Division', 'Corporate Services Division'), ('Office of the CEO', 'Office of the CEO'), ('Office of the Minister', 'Office of the Minister'), ('Information Technology and Communication Division', 'Information Technology and Communication Division'), ('Finacial Framework Division', 'Finacial Framework Division'), ('Procurement Division', 'Procurement Division'), ('Treasury Division', 'Treasury Division'), ('Budget Division', 'Budget Division'), ('Aid and Projects Division', 'Aid and Projects Division'), ('Economic and Fiscal Policy Division', 'Economic and Fiscal Policy Division'), ('Resilience Division', 'Resilience Division'), ('SUB EUA', 'SUB EUA'), ('SUB VAVAU', 'SUB VAVAU'), ('SUB HAAPAI', 'SUB HAAPAI')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fy2020_2021',
            name='Remarks',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
