# Generated by Django 3.0.6 on 2020-07-21 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20200721_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fy2020_2021',
            name='Band',
        ),
        migrations.RemoveField(
            model_name='fy2020_2021',
            name='Division',
        ),
        migrations.RemoveField(
            model_name='fy2020_2021',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='fy2020_2021',
            name='Last_Name',
        ),
        migrations.RemoveField(
            model_name='fy2020_2021',
            name='Position',
        ),
        migrations.AddField(
            model_name='fy2020_2021',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.Staff'),
        ),
    ]
