# Generated by Django 3.0.6 on 2020-07-27 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20200722_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='Code',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='Last_Name',
        ),
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.CharField(default='default', max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fy2020_2021',
            name='Remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fy2020_2021',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.Staff'),
        ),
    ]
